/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicios9;

/**
 *
 * @author moise
 */
public class Formulario extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        javax.swing.ButtonGroup grupoGenero = new javax.swing.ButtonGroup();
       grupoGenero.add(JRHOMBRE);
       grupoGenero.add(JRMUJER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbnombre = new javax.swing.JLabel();
        lbapellidos = new javax.swing.JLabel();
        lbpassword = new javax.swing.JLabel();
        lbgenero = new javax.swing.JLabel();
        tfldnombre = new javax.swing.JTextField();
        tldfapellidos = new javax.swing.JTextField();
        JRMUJER = new javax.swing.JRadioButton();
        JRHOMBRE = new javax.swing.JRadioButton();
        BUTTONENVIAR = new javax.swing.JButton();
        JCDEACUERDO = new javax.swing.JCheckBox();
        lbgenero1 = new javax.swing.JLabel();
        tldfpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbnombre.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbnombre.setText("Nombre");

        lbapellidos.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbapellidos.setText("Apellidos");

        lbpassword.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbpassword.setText("Password");

        lbgenero.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbgenero.setText("Estas de acuerdo?");

        JRMUJER.setText("M");

        JRHOMBRE.setText(" H");

        BUTTONENVIAR.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BUTTONENVIAR.setText("Enviar");
        BUTTONENVIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTONENVIARActionPerformed(evt);
            }
        });

        lbgenero1.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbgenero1.setText("Genero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbgenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfldnombre)
                            .addComponent(tldfapellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JRHOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JRMUJER, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tldfpassword)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BUTTONENVIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCDEACUERDO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbnombre)
                    .addComponent(tfldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbapellidos)
                    .addComponent(tldfapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbpassword)
                    .addComponent(tldfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbgenero1)
                    .addComponent(JRHOMBRE)
                    .addComponent(JRMUJER))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbgenero)
                    .addComponent(JCDEACUERDO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(BUTTONENVIAR)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTTONENVIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTONENVIARActionPerformed
          String nombre = tfldnombre.getText().trim();
    String apellidos = tldfapellidos.getText().trim();
    String password = new String(tldfpassword.getPassword());

    // Validar campos vacíos
    if (nombre.isEmpty() || apellidos.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe llenar todos los campos.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar género seleccionado
    if (!JRHOMBRE.isSelected() && !JRMUJER.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe seleccionar un género.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar el checkbox
    if (!JCDEACUERDO.isSelected()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Debe estar de acuerdo para continuar.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Si todo está correcto
    javax.swing.JOptionPane.showMessageDialog(this,
            "Formulario enviado correctamente.",
            "Éxito",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);        // TODO add your handling code here:
    }//GEN-LAST:event_BUTTONENVIARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTONENVIAR;
    private javax.swing.JCheckBox JCDEACUERDO;
    private javax.swing.JRadioButton JRHOMBRE;
    private javax.swing.JRadioButton JRMUJER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbapellidos;
    private javax.swing.JLabel lbgenero;
    private javax.swing.JLabel lbgenero1;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbpassword;
    private javax.swing.JTextField tfldnombre;
    private javax.swing.JTextField tldfapellidos;
    private javax.swing.JPasswordField tldfpassword;
    // End of variables declaration//GEN-END:variables
}
