/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareasinferface;

/**
 *
 * @author moise
 */
public class Imitador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Imitador.class.getName());

    /**
     * Creates new form Imitador
     */
    public Imitador() {
        initComponents();
        activarImitador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        JROPCION2 = new javax.swing.JRadioButton();
        JROPCION3 = new javax.swing.JRadioButton();
        JROPCION1 = new javax.swing.JRadioButton();
        JCOPCION2 = new javax.swing.JCheckBox();
        JCOPCION3 = new javax.swing.JCheckBox();
        JCOPCION1 = new javax.swing.JCheckBox();
        TEXTFIELD1 = new javax.swing.JTextField();
        jSpinnerEspejo = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        JROPCIONESPEJO1 = new javax.swing.JRadioButton();
        JROPCIONESPEJO2 = new javax.swing.JRadioButton();
        JROPCIONESPEJO3 = new javax.swing.JRadioButton();
        JCOPCIONESPEJO1 = new javax.swing.JCheckBox();
        JCOPCIONESPEJO2 = new javax.swing.JCheckBox();
        JCOPCIONESPEJO3 = new javax.swing.JCheckBox();
        TEXTFIELDESPEJO = new javax.swing.JTextField();
        jComboBoxEspejo = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();

        jLabel2.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel1.setText("Original");

        JROPCION2.setText("Opcion 2");

        JROPCION3.setText("Opcion 3");

        JROPCION1.setText("Opcion 1");

        JCOPCION2.setText("Opcion 2");

        JCOPCION3.setText("Opcion 3");

        JCOPCION1.setText("Opcion 1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel3.setText("Espejo");

        JROPCIONESPEJO1.setText("Opcion 1");

        JROPCIONESPEJO2.setText("Opcion 2");

        JROPCIONESPEJO3.setText("Opcion 3");

        JCOPCIONESPEJO1.setText("Opcion 1");

        JCOPCIONESPEJO2.setText("Opcion 2");

        JCOPCIONESPEJO3.setText("Opcion 3");

        jComboBoxEspejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JROPCION2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCOPCION2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(JROPCION3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JCOPCION3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSpinner1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JROPCION1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCOPCION1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TEXTFIELD1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JROPCIONESPEJO3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCOPCIONESPEJO3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jSpinnerEspejo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JROPCIONESPEJO2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCOPCIONESPEJO2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBoxEspejo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JROPCIONESPEJO1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JCOPCIONESPEJO1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(TEXTFIELDESPEJO, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCION1)
                    .addComponent(JCOPCION1)
                    .addComponent(TEXTFIELD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCION2)
                    .addComponent(JCOPCION2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCION3)
                    .addComponent(JCOPCION3)
                    .addComponent(jSpinner1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCIONESPEJO1)
                    .addComponent(JCOPCIONESPEJO1)
                    .addComponent(TEXTFIELDESPEJO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCIONESPEJO2)
                    .addComponent(JCOPCIONESPEJO2)
                    .addComponent(jComboBoxEspejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JROPCIONESPEJO3)
                    .addComponent(JCOPCIONESPEJO3)
                    .addComponent(jSpinnerEspejo))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private void activarImitador() {

        // TEXTFIELD
        TEXTFIELD1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { TEXTFIELDESPEJO.setText(TEXTFIELD1.getText()); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { TEXTFIELDESPEJO.setText(TEXTFIELD1.getText()); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { TEXTFIELDESPEJO.setText(TEXTFIELD1.getText()); }
        });

        // RADIOS
        JROPCION1.addActionListener(e -> JROPCIONESPEJO1.setSelected(JROPCION1.isSelected()));
        JROPCION2.addActionListener(e -> JROPCIONESPEJO2.setSelected(JROPCION2.isSelected()));
        JROPCION3.addActionListener(e -> JROPCIONESPEJO3.setSelected(JROPCION3.isSelected()));

        // CHECKBOXES
        JCOPCION1.addItemListener(e -> JCOPCIONESPEJO1.setSelected(JCOPCION1.isSelected()));
        JCOPCION2.addItemListener(e -> JCOPCIONESPEJO2.setSelected(JCOPCION2.isSelected()));
        JCOPCION3.addItemListener(e -> JCOPCIONESPEJO3.setSelected(JCOPCION3.isSelected()));

        // COMBOBOX
        jComboBox1.addActionListener(e -> jComboBoxEspejo.setSelectedIndex(jComboBox1.getSelectedIndex()));

        // SPINNER
        jSpinner1.addChangeListener(e -> jSpinnerEspejo.setValue(jSpinner1.getValue()));

        // DESACTIVAR ESPEJO PARA QUE NO SE PUEDA EDITAR
        bloquearEspejo();
    }

    private void bloquearEspejo() {
        TEXTFIELDESPEJO.setEnabled(false);
        JROPCIONESPEJO1.setEnabled(false);
        JROPCIONESPEJO2.setEnabled(false);
        JROPCIONESPEJO3.setEnabled(false);
        JCOPCIONESPEJO1.setEnabled(false);
        JCOPCIONESPEJO2.setEnabled(false);
        JCOPCIONESPEJO3.setEnabled(false);
        jComboBoxEspejo.setEnabled(false);
        jSpinnerEspejo.setEnabled(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        java.awt.EventQueue.invokeLater(() -> new Imitador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox JCOPCION1;
    private javax.swing.JCheckBox JCOPCION2;
    private javax.swing.JCheckBox JCOPCION3;
    private javax.swing.JCheckBox JCOPCIONESPEJO1;
    private javax.swing.JCheckBox JCOPCIONESPEJO2;
    private javax.swing.JCheckBox JCOPCIONESPEJO3;
    private javax.swing.JRadioButton JROPCION1;
    private javax.swing.JRadioButton JROPCION2;
    private javax.swing.JRadioButton JROPCION3;
    private javax.swing.JRadioButton JROPCIONESPEJO1;
    private javax.swing.JRadioButton JROPCIONESPEJO2;
    private javax.swing.JRadioButton JROPCIONESPEJO3;
    private javax.swing.JTextField TEXTFIELD1;
    private javax.swing.JTextField TEXTFIELDESPEJO;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxEspejo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerEspejo;
    // End of variables declaration//GEN-END:variables
}
